### ISSUE TITLE
some indicator that ai-cli-lib is enabled and/or running

### ISSUE THREAD

**Issue by dmgerman** [dspinellis/ai-cli-lib#10]
Have some way to know if ai-cli-lib has been loaded. It could be a simple message to stdout, or a different promt. 

Similarly, is it possible to have a way to know if the current prompt has been submitted and it is waiting for a response.

**Comment by dspinellis** [comment]
Good points. A message to stderr / prompt output should be the way to go.

**Comment by dspinellis** [comment]
Adding an indicator that ai-cli-lib is running is disrupting in bash, because for some reason in re-loads dynamic libraries at every prompt invocation. (You can try it out by setting verbose.)

The need to know that the prompt has been submitted is now satisfied by the prompt automatically changing to a comment before submitting it (9547b0c5cdc13db0c8).
